# === Stage 1: Build ===
FROM node:24-alpine AS builder

WORKDIR /app

ARG VITE_API_URL
ARG VITE_SOCKET_URL

ENV VITE_API_URL=$VITE_API_URL
ENV VITE_SOCKET_URL=$VITE_SOCKET_URL

COPY package*.json ./

RUN npm ci && npm cache clean --force

COPY . .

RUN npm run build

# === Stage 2: Run ===
FROM nginx:alpine

COPY --from=builder /app/dist/ /usr/share/nginx/html

COPY default.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]