# === Stage 1: Build ===
FROM node:24-alpine AS builder

WORKDIR /app

COPY package*.json ./

RUN npm ci && npm cache clean --force

COPY . .

RUN npm run build

RUN npm run copy:migrations

# === Stage 2: Run ===
FROM node:24-alpine

WORKDIR /app

COPY package*.json ./

RUN npm ci --only=production && npm cache clean --force

COPY --from=builder /app/dist /app/dist

EXPOSE 8000

CMD ["npm", "run", "start"]