CREATE TABLE IF NOT EXISTS users (
  id SERIAL PRIMARY KEY,
  username VARCHAR(50) UNIQUE NOT NULL,
  email VARCHAR(100) UNIQUE NOT NULL,
  password VARCHAR(255) NOT NULL,
  rooms UUID[] NOT NULL DEFAULT [],  
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);